import type { SupportedFormat, FilterListMetadata } from "../types.js";

export function generateHeader(
  meta: FilterListMetadata,
  format: SupportedFormat,
): string {
  const isBangComment =
    format === "adguard" || format === "abp" || format === "all";
  const c = isBangComment ? "! " : "# ";

  // Common header for all formats
  const commonHeader = [
    c + "Title: " + meta.title,
    c + "Description: " + meta.description,
    c + "Homepage: " + meta.homepage,
    c + "Version: " + meta.version,
    c + "Last updated: " + meta.lastUpdated,
  ];

  // Format-specific additions
  const additionalLines: string[] = [];

  switch (format) {
    case "hosts":
      additionalLines.push(
        c + "Format: Hosts",
        c + "This file is in hosts file format and can be used as system hosts file",
      );
      break;
    case "dnsmasq":
      additionalLines.push(
        c + "Format: dnsmasq",
        c + "This file contains rules suitable for dnsmasq DNS server",
      );
      break;
    case "unbound":
      additionalLines.push(
        c + "Format: Unbound",
        c + "This file contains rules suitable for Unbound DNS server",
      );
      break;
    case "bind":
      additionalLines.push(
        c + "Format: BIND",
        c + "This file contains rules suitable for BIND DNS server",
      );
      break;
    case "privoxy":
      additionalLines.push(
        c + "Format: Privoxy",
        c + "This file contains rules suitable for Privoxy proxy server",
      );
      break;
    case "shadowrocket":
      additionalLines.push(
        c + "Format: Shadowrocket",
        c + "This file contains rules suitable for Shadowrocket app",
      );
      break;
    case "adguard":
      additionalLines.push(
        c + "Format: AdGuard",
        c + "This file contains rules optimized for AdGuard products",
      );
      break;
    case "abp":
      additionalLines.push(
        c + "Format: ABP",
        c + "This file contains rules compatible with Adblock Plus",
      );
      break;
    case "all":
      additionalLines.push(
        c + "Format: All",
        c + "This file contains all rules in their original formats",
      );
      break;
  }

  // Add statistics if available
  if (meta.stats) {
    additionalLines.push(
      c + "Total Rules: " + (meta.stats.totalRules || "N/A"),
      c + "Blocking Rules: " + (meta.stats.blockingRules || "N/A"),
      c + "Exception Rules: " + (meta.stats.exceptionRules || "N/A"),
    );
  }

  // Add license and generator info
  additionalLines.push(
    c + "License: " + (meta.license || "Unspecified"),
    c + "Generated by Blockingmachine " + (meta.generatorVersion || ""),
    "", // Empty line at the end
  );

  return [...commonHeader, ...additionalLines].join("\n");
}
