import {
  generateFilterList,
  formatRule,
  type FilterMetadata,
} from "../export/advanced-formatter.js";
import { parseFilterList } from "../RuleProcessor.js";
import type { StoredRule } from "../RuleStore.js";

describe("advanced-formatter", () => {
  const metadata: FilterMetadata = {
    title: "Test Blocklist",
    description: "A test list for verification",
    homepage: "https://example.com",
    version: "1.0.0",
    lastUpdated: "2026-09-14T00:00:00.000Z",
    stats: {
      totalRules: 4,
      uniqueRules: 4,
      blockingRules: 3,
      exceptionRules: 1,
    },
  };

  const sampleRulesText = `
||analytics.google.com^
||ads.facebook.com^$third-party
0.0.0.0 telemetry.microsoft.com
@@||allowed-cdn.com^
  `.trim();

  const rules: StoredRule[] = parseFilterList(sampleRulesText, "test-source");

  test("generates proper AdGuard formatted output with full header", () => {
    const output = generateFilterList(rules, metadata, "adguard");

    expect(output).toContain("[Adblock Plus 2.0]");
    expect(output).toContain("! Title: Test Blocklist");
    expect(output).toContain("! Format: AdGuard");
    expect(output).toContain("! Generated by Blockingmachine v1.0.0");
    // Ensure the old operator precedence bug is fixed (! on its own line)
    expect(output).not.toMatch(/^!\s*$/m);
    expect(output).toContain("||analytics.google.com^");
    expect(output).toContain("@@||allowed-cdn.com^");
  });

  test("generates hosts format with domain rules and exception comments", () => {
    const output = generateFilterList(rules, metadata, "hosts");

    expect(output).toContain("127.0.0.1 localhost");
    expect(output).toContain("0.0.0.0 analytics.google.com");
    expect(output).toContain("0.0.0.0 ads.facebook.com");
    expect(output).toContain("0.0.0.0 telemetry.microsoft.com");
    expect(output).toContain("# EXCEPTION: @@||allowed-cdn.com^");
  });

  test("generates dnsmasq format correctly", () => {
    const output = generateFilterList(rules, metadata, "dnsmasq");

    expect(output).toContain("address=/analytics.google.com/0.0.0.0");
    expect(output).toContain("address=/ads.facebook.com/0.0.0.0");
    expect(output).toContain("address=/telemetry.microsoft.com/0.0.0.0");
    expect(output).toContain("# EXCEPTION: @@||allowed-cdn.com^");
  });

  test("generates unbound format correctly", () => {
    const output = generateFilterList(rules, metadata, "unbound");

    expect(output).toContain('local-zone: "analytics.google.com" always_nxdomain');
    expect(output).toContain('local-zone: "ads.facebook.com" always_nxdomain');
    expect(output).toContain('local-zone: "telemetry.microsoft.com" always_nxdomain');
    expect(output).toContain("# EXCEPTION: @@||allowed-cdn.com^");
  });

  test("generates plain domains format correctly", () => {
    const output = generateFilterList(rules, metadata, "domains");

    expect(output).toContain("analytics.google.com");
    expect(output).toContain("ads.facebook.com");
    expect(output).toContain("telemetry.microsoft.com");
    expect(output).toContain("# EXCEPTION: @@||allowed-cdn.com^");
  });

  test("formatRule handles fallback when domain is on metadata or raw", () => {
    const ruleWithoutDomain: StoredRule = {
      raw: "||doubleclick.net^",
      originalRule: "||doubleclick.net^",
      hash: "123",
      type: "blocking",
      metadata: {
        sources: ["test"],
        dateAdded: new Date(),
        lastUpdated: new Date(),
        enabled: true,
        sourceInfo: { category: "ads", trusted: true, url: "test", priority: 1 },
        tags: [],
      },
    };

    expect(formatRule(ruleWithoutDomain, "hosts")).toBe("0.0.0.0 doubleclick.net");
    expect(formatRule(ruleWithoutDomain, "dnsmasq")).toBe("address=/doubleclick.net/0.0.0.0");
    expect(formatRule(ruleWithoutDomain, "domains")).toBe("doubleclick.net");
  });
});
